name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
      - run: echo "this is printed from yaml file"
      - run: echo ${{secrets.MYTESTSECRET}}
      - name: "set env variable with secret value"
        env:
              myEnvVar: My env variable value
              myEnvSecre: ${{secrets.MYTESTSECRET}}
        run: echo "${env.myEnvVar} ${env.myEnvSecre}"

