name: learn-github-actions
# on: [push]
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
      - run: echo "this is printed from yaml file"
      - run: echo ${{secrets.MYTESTSECRET}}
      - name: "set env variable with secret value"
        env:
              myEnvVar: My env variable value
              myEnvSecre: ${{secrets.MYTESTSECRET}}
        run: echo "$myEnvVar $myEnvSecre"

